# Reference: https://github.com/probot/settings#github-settings

repository:
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks: null
      enforce_admins: false
      restrictions: null

teams:
  - name: TAs
    permission: push
  - name: Robots
    permission: pull
  - name: Instructors
    permission: admin
